### ISSUE TITLE
Firebase Cloud Messaging

### ISSUE THREAD

**Issue by davorpeic** [Rias500/craft-notifications#12]
Hi,

we added new channel to be able to send push notifications to our mobile app with Firebase Messaging, would you be interested adding this as a built-in feature so we could plan a PR in the near future?

Thanks
Davor

**Comment by Rias500** [comment]
Hi @davorpeic I'd like to keep the core clean, you're free to release a plugin just like I did for a Telegram notification channel: https://github.com/rias500/craft-telegram-notification-channel

**Comment by davorpeic** [comment]
Sorry for late answer
that sounds awesome and yes, you are right, its better not to fill it
