### ISSUE TITLE
Notifications on user subscription

### ISSUE THREAD

**Issue by giacomocarra** [Rias500/craft-notifications#14]
Hi, I'm able to send mail notifications on entry save.
Is it possible even on user subscription?
This is what I tried (without success):

config/notifications.php

`'notifications' => [
        [
            'class' => \craft\elements\User::class,
            'event' => \craft\elements\User::EVENT_AFTER_SAVE,
            'notification' => \app\notifications\UserSubscribed::class,
        ],
    ],`

notifications/UserSubscribed.php

`
public function via()
    {
        $user = $this->event->sender;

        if ($user->groups->handle === 'users' && !$this->event->isNew) {
            return [
                'database' => Craft::$app->getUsers()->getUserByUsernameOrEmail('giacomo.carra@paxxion.com'),
            ];
        }

        return [
            'mail' => 'giacomo.carra@paxxion.com',
        ];

        return [];
    }
`

**Comment by Rias500** [comment]
It is possible to attach notifications to any event, but what you want to do after that I can't really help with as it's very specific to the events being thrown and what's available in them.

Sending a notification when a user is created should be about the same as when an entry is created.

**Comment by gioppe** [comment]
Just use:
```
if( $this->event->isNew ) {
  return [ 'mail' => 'giacomo.carra@paxxion.com' ];
}
```

**Comment by giacomocarra** [comment]
> Just use:
> 
> ```
> if( $this->event->isNew ) {
>   return [ 'mail' => 'giacomo.carra@paxxion.com' ];
> }
> ```

It works! Thank you
