### ISSUE TITLE
Emails sending multiple times?

### ISSUE THREAD

**Issue by mikestecker** [Rias500/craft-notifications#16]
I'm only testing on my local install, but it seems that emails are being sent 3-4 times for some reason. 

My setup is pretty simple:

File `config/notifications.php`:
```
<?php
return [
    'notifications' => [
        [
            'class' => \craft\elements\Entry::class,
            'event' => \craft\elements\Entry::EVENT_AFTER_SAVE,
            'notification' => \app\notifications\ApplicationSubmitted::class,
        ],
    ],
];
```

File `notifications/ApplicationSubmitted.php`:
```
<?php

namespace app\notifications;

use Craft;
use craft\elements\Entry;
use craft\helpers\ArrayHelper;
use craft\mail\Message;
use rias\notifications\models\Notification;

class ApplicationSubmitted extends Notification
{
    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct($event = null)
    {
        parent::__construct($event);
    }

    /**
     * Get the notification's delivery channels.
     *
     * @return array
     */
    public function via()
    {
        $entry = $this->event->sender;

        if ($entry->section->handle === 'test' && !$this->event->isNew) {
            return [
                'mail' => 'mike@stecker.me'
            ];
        }

        return [];
    }

    public function toDatabase()
    {
        return ArrayHelper::toArray($this);
    }

    public function toMail($notifiable)
    {
        $title = $this->event->sender->title;

        $message = new Message();
        $message->setTo($notifiable);
        $message->setSubject("New Applicant: {$title}");
        $message->setHtmlBody("
            <h3>A new application was submitted via the website.</h3>
            <p>Name: {$title}</p>
        ");

        return $message;
    }
}
```

**Comment by mikestecker** [comment]
For what it's worth, on my local install I have Craft set up to simply use Sendmail as well. I haven't configured any SMTP services or anything.

**Comment by Rias500** [comment]
You have this check `if ($entry->section->handle === 'test' && !$this->event->isNew) {` which means the notifications are sending when it isn't a new entry.

Are you sure this is what you want? I figure you'd want it only when it is a new submission.

I assume you're using multisite, as entries get saved multiple times (once for each site), which will cause this to happen, you could add an extra check for the siteId or even add a cache or session key to know you've already sent a notification.

**Comment by mikestecker** [comment]
Ahhh overlooked the `!` in there, I pulled that from some example somewhere, must not have looked closely enough. Yeah, I'm wanting to get notifications for new submissions.

Good call on the multisite! That would make sense as to why I'm getting a number of emails, one for each site.

I'll add my updated code soon to this issue and close it once I get it working, that way others can see the proper code for checking multisite.

**Comment by mikestecker** [comment]
So I'm thinking it should be `if ($entry->section->handle === 'test' && $this->$siteId == '6' && $this->event->isNew) {` which adds my section handle and `siteId`... I'm submitting the same `siteId` with the guest entries form, so that should do it.
