### ISSUE TITLE
Including entry fields in email notification

### ISSUE THREAD

**Issue by tidy** [Rias500/craft-notifications#18]
Thanks for this great plugin. I am using it to send an email notification when a new entry is added.

One thing I am stuck on is how to include fields from the new entry (other than the title) in the email.

I tried looking at the $this->event object and saw a customFields array within in with the various values, but I couldn't seem to find the code that would work here. If this is possible, could you tell me the syntax to use to output a field value in the email? Many thanks.

**Comment by Rias500** [comment]
Hi, in the event you should just be able to assign the event sender to an entry variable:

```php
$entry = $this->event->sender;
```

You can access every custom field from the entry: `$entry->my_field`

**Comment by tidy** [comment]
Brilliant - many thanks for explaining this.
