### ISSUE TITLE
Detail how to access updated Entry info from Entry:EVENT_AFTER_SAVE

### ISSUE THREAD

**Issue by MozJon** [Rias500/craft-notifications#6]
I can't seem to get the Craft event info which I needed for the details of me Slack message.
I had assumed it would be data on `$notifiable` when defining `public function toSlack($notifiable)`
This however errors out. 
If it is possible could you update the documentation with examples of collecting the data from an event such as which entry was changed.

**Comment by Rias500** [comment]
You can access all the information of the event with `$this->event` in your notification.
