### ISSUE TITLE
What Might Cause Notifications to get Stuck In Queue?

### ISSUE THREAD

**Issue by smockensturm** [Rias500/craft-notifications#7]
Sending Notifcations task progress bar in Craft CP just keeps spinning. Never releases. Have to manually clear out the queue in the Craft database.

Where should I be looking for errors?

Set up out of the box per instructions.

**Comment by Rias500** [comment]
`storage/logs/queue.log` or `storage/logs/web.log` should have an error if the queue tasks get stuck.

**Comment by smockensturm** [comment]
thanks.

this error mean anything to you, then? that's the only error I see. looks like it's happening trying to unpack your longblob job column in the queue.

`2018-05-14 09:19:32 [192.168.10.1][1][-][error][UnexpectedValueException] UnexpectedValueException: Error at offset 0 of 2 bytes in /home/vagrant/sites/kingston/vendor/yiisoft/yii2-queue/src/serializers/PhpSerializer.php:32`

**Comment by smockensturm** [comment]
There is a checkbox fieldtype in the section for which we'd like to send a notification when a new entry is posted in said section.

Removing this checkbox fieldtype eliminates the stuck queue issue when we save an entry. Everything works fine.

So... what to do?

**Comment by Rias500** [comment]
This seems like the same issue as described here:

https://github.com/Rias500/craft-scout/issues/6

It's an issue with how Craft/Yii serializes/deserializes objects, you have to cast checkbox fields manually to an array.

**Comment by smockensturm** [comment]
Great. Where?

Do I have to alter the plugin or can I do this somewhere in the configuration setup?

**Comment by Rias500** [comment]
I'll have to find a solution for it, didn't mean to close it

**Comment by smockensturm** [comment]
Great. Looking forward to it. Otherwise we can't really use this. Thank you.

Just curious, is this a good idea? What are you going to do when a super complex entry is involved with maybe a giant Matrix field and perhaps a bunch of other complex field types? Serialize the whole thing?

**Comment by Rias500** [comment]
I'll work on it this weekend, but the plan for now is removing the Queued part of the notifications until I find a better way to do it.

**Comment by Rias500** [comment]
Notifications are no longer queued so this should solve your issue.
