### ISSUE TITLE
By Section Type

### ISSUE THREAD

**Issue by smockensturm** [Rias500/craft-notifications#9]
Hi. This is really helpful and works great.

`if ($entry->section->handle === 'blog' && !$this->event->isNew)`

How might I check for section **type**, please?

**Comment by theskyfloor** [comment]
@smockensturm do you mean entry type?

**Comment by smockensturm** [comment]
Maybe. Say we have a section called Forms with two types: Long and Short. Would that be `$entry->type->handle` or `$entry->section->type-handle`

**Comment by theskyfloor** [comment]
`$entry->type->handle` should do the trick. Let me know!
